name: Publish package ucam-design-system to Github Package Registry

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - projects/ucam-design-system/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
          scope: "@universidade-candido-mendes"
      - name: Install npm Packages
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps --registry=https://registry.npmjs.org/
      - name: Build
        run: npm run build ucam-design-system
      - name: Publish to GitHub Packages
        if: success()
        run: cd dist/ucam-design-system && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
